### ISSUE TITLE
faq: Pre-reserve DOI button

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo-docs-user#47]
This was also one of the user's suggestions. This question comes up once in a while, perhaps we should add to the FAQ?

**Comment by krzysztof** [comment]
Added to FAQ

**Comment by RaoOfPhysics** [comment]
@krzysztof: Does this also work for the [Github&harr;Zenodo connection](https://guides.github.com/activities/citable-code/)? i.e., can I reserve a DOI for a repo before making a release so that the docs in the repo snapshot can reference the DOI?

**Comment by krzysztof** [comment]
@RaoOfPhysics Unfortunately there's no way to do it with GitHub integration, other than, of course, fetching a ZIP from GitHub and uploading the code manually as a regular package. If your intention is to have a DOI badge in the repo, you can always use Concept DOI which doesn't change: https://github.com/zenodo/zenodo/issues/1164

**Comment by RaoOfPhysics** [comment]
Thanks, @krzysztof. Will look into Concept DOIs.

**Comment by nheeren** [comment]
I would have a few questions (which you may want to clarify in the DOI):
- Is the pre-reserved DOI also a concept DOI?
- Does a pre-reserved DOI expire?

**Comment by allefeld** [comment]
It is really unforunate that it isn't possible to get a DOI before a GitHub release. In the interest of reproducibility it is important to cite the exact version of the used software. I'd expect that most users download and install a package and don't return to its Zenodo or GitHub page later, so optimally the version-specific DOI should be in the documentation (README) within the downloaded package.

This would be less important if the concept DOI would resolve to a landing page which lists all versions, but that isn't the case either. And I can't even get a concept DOI before the first release.

> Unfortunately there's no way to do it with GitHub integration

Do you mean it's not implemented, or you don't see a way to implement it?

If the latter, I don't understand why. Just as there's a "Get a DOI now!" button on the upload page, there could be such a button on the GitHub repository page:
![image](https://github.com/zenodo/zenodo-docs-user/assets/1738353/64dd7433-f574-409a-9d75-d59ef7f701a8)

**Comment by robna** [comment]
This one is closed, but I think the function of DOI reservation for Github repositories would be very useful. I opened #121 specifically for this.
